services:
  backend:
    build: .
    container_name: clouddocs_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PORT=8000
    restart: always

  # Sau này FE làm xong thì chỉ cần mở comment phần này ra:
  # frontend:
  #   build: ./frontend
  #   container_name: clouddocs_frontend
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #   restart: always